/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CvRouteImport } from './routes/cv'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BlogsRouteRouteImport } from './routes/blogs/route'
import { Route as ApiRouteRouteImport } from './routes/api/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as BlogsExampleRouteImport } from './routes/blogs/example'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as BlogsSqlVsNosqlIsBadComparisonChar123LangChar125RouteImport } from './routes/blogs/sql-vs-nosql-is-bad-comparison.{-$lang}'

const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRouteRoute = BlogsRouteRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouteRoute = ApiRouteRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRouteRoute,
} as any)
const BlogsExampleRoute = BlogsExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => BlogsRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiRouteRoute,
} as any)
const BlogsSqlVsNosqlIsBadComparisonChar123LangChar125Route =
  BlogsSqlVsNosqlIsBadComparisonChar123LangChar125RouteImport.update({
    id: '/sql-vs-nosql-is-bad-comparison/{-$lang}',
    path: '/sql-vs-nosql-is-bad-comparison/{-$lang}',
    getParentRoute: () => BlogsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/blogs': typeof BlogsRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/cv': typeof CvRoute
  '/api/$': typeof ApiSplatRoute
  '/blogs/example': typeof BlogsExampleRoute
  '/blogs/': typeof BlogsIndexRoute
  '/blogs/sql-vs-nosql-is-bad-comparison/{-$lang}': typeof BlogsSqlVsNosqlIsBadComparisonChar123LangChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/cv': typeof CvRoute
  '/api/$': typeof ApiSplatRoute
  '/blogs/example': typeof BlogsExampleRoute
  '/blogs': typeof BlogsIndexRoute
  '/blogs/sql-vs-nosql-is-bad-comparison/{-$lang}': typeof BlogsSqlVsNosqlIsBadComparisonChar123LangChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/blogs': typeof BlogsRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/cv': typeof CvRoute
  '/api/$': typeof ApiSplatRoute
  '/blogs/example': typeof BlogsExampleRoute
  '/blogs/': typeof BlogsIndexRoute
  '/blogs/sql-vs-nosql-is-bad-comparison/{-$lang}': typeof BlogsSqlVsNosqlIsBadComparisonChar123LangChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/blogs'
    | '/$'
    | '/cv'
    | '/api/$'
    | '/blogs/example'
    | '/blogs/'
    | '/blogs/sql-vs-nosql-is-bad-comparison/{-$lang}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/$'
    | '/cv'
    | '/api/$'
    | '/blogs/example'
    | '/blogs'
    | '/blogs/sql-vs-nosql-is-bad-comparison/{-$lang}'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/blogs'
    | '/$'
    | '/cv'
    | '/api/$'
    | '/blogs/example'
    | '/blogs/'
    | '/blogs/sql-vs-nosql-is-bad-comparison/{-$lang}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRouteRoute: typeof ApiRouteRouteWithChildren
  BlogsRouteRoute: typeof BlogsRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  CvRoute: typeof CvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRouteRoute
    }
    '/blogs/example': {
      id: '/blogs/example'
      path: '/example'
      fullPath: '/blogs/example'
      preLoaderRoute: typeof BlogsExampleRouteImport
      parentRoute: typeof BlogsRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/blogs/sql-vs-nosql-is-bad-comparison/{-$lang}': {
      id: '/blogs/sql-vs-nosql-is-bad-comparison/{-$lang}'
      path: '/sql-vs-nosql-is-bad-comparison/{-$lang}'
      fullPath: '/blogs/sql-vs-nosql-is-bad-comparison/{-$lang}'
      preLoaderRoute: typeof BlogsSqlVsNosqlIsBadComparisonChar123LangChar125RouteImport
      parentRoute: typeof BlogsRouteRoute
    }
  }
}

interface ApiRouteRouteChildren {
  ApiSplatRoute: typeof ApiSplatRoute
}

const ApiRouteRouteChildren: ApiRouteRouteChildren = {
  ApiSplatRoute: ApiSplatRoute,
}

const ApiRouteRouteWithChildren = ApiRouteRoute._addFileChildren(
  ApiRouteRouteChildren,
)

interface BlogsRouteRouteChildren {
  BlogsExampleRoute: typeof BlogsExampleRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  BlogsSqlVsNosqlIsBadComparisonChar123LangChar125Route: typeof BlogsSqlVsNosqlIsBadComparisonChar123LangChar125Route
}

const BlogsRouteRouteChildren: BlogsRouteRouteChildren = {
  BlogsExampleRoute: BlogsExampleRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  BlogsSqlVsNosqlIsBadComparisonChar123LangChar125Route:
    BlogsSqlVsNosqlIsBadComparisonChar123LangChar125Route,
}

const BlogsRouteRouteWithChildren = BlogsRouteRoute._addFileChildren(
  BlogsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRouteRoute: ApiRouteRouteWithChildren,
  BlogsRouteRoute: BlogsRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  CvRoute: CvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
