/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BlogsRouteRouteImport } from './routes/blogs/route'
import { Route as ApiRouteRouteImport } from './routes/api/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as BlogsExampleRouteImport } from './routes/blogs/example'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRouteRoute = BlogsRouteRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouteRoute = ApiRouteRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRouteRoute,
} as any)
const BlogsExampleRoute = BlogsExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => BlogsRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/blogs': typeof BlogsRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/api/$': typeof ApiSplatRoute
  '/blogs/example': typeof BlogsExampleRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/api/$': typeof ApiSplatRoute
  '/blogs/example': typeof BlogsExampleRoute
  '/blogs': typeof BlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/blogs': typeof BlogsRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/api/$': typeof ApiSplatRoute
  '/blogs/example': typeof BlogsExampleRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/blogs'
    | '/$'
    | '/api/$'
    | '/blogs/example'
    | '/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api' | '/$' | '/api/$' | '/blogs/example' | '/blogs'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/blogs'
    | '/$'
    | '/api/$'
    | '/blogs/example'
    | '/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRouteRoute: typeof ApiRouteRouteWithChildren
  BlogsRouteRoute: typeof BlogsRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRouteRoute
    }
    '/blogs/example': {
      id: '/blogs/example'
      path: '/example'
      fullPath: '/blogs/example'
      preLoaderRoute: typeof BlogsExampleRouteImport
      parentRoute: typeof BlogsRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof ApiRouteRoute
    }
  }
}

interface ApiRouteRouteChildren {
  ApiSplatRoute: typeof ApiSplatRoute
}

const ApiRouteRouteChildren: ApiRouteRouteChildren = {
  ApiSplatRoute: ApiSplatRoute,
}

const ApiRouteRouteWithChildren = ApiRouteRoute._addFileChildren(
  ApiRouteRouteChildren,
)

interface BlogsRouteRouteChildren {
  BlogsExampleRoute: typeof BlogsExampleRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteRouteChildren: BlogsRouteRouteChildren = {
  BlogsExampleRoute: BlogsExampleRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteRouteWithChildren = BlogsRouteRoute._addFileChildren(
  BlogsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRouteRoute: ApiRouteRouteWithChildren,
  BlogsRouteRoute: BlogsRouteRouteWithChildren,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
